apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 3 # Number of replicas (instances) to run
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: hub.docker.com/cloud_native:4_2C
          ports:
            - containerPort: 3000 # Port your application listens on
