version: '3'
services:
  app:
    build: .
    image: thenusan/cloud_native:6.2P
    ports:
      - "8080:3000"
    container_name: node-calculator
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
