apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  type: NodePort # Expose the service on a specific port on each node
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 8080 # Port exposed by the service
      targetPort: 3000 # Port your application listens on
