apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    tier: frontend
    app: nodejs-app
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  ports:
    - name: myport
      port: 8037
      protocol: TCP
      targetPort: 3040
  type: LoadBalancer
